// ═══════════════════════════════════════════════════════════
// DATA + TRANSLATIONS for ❤️U Festival App
// ═══════════════════════════════════════════════════════════

const BRAND = {
  vermilion: '#F03228',
  cerulean:  '#247BA0',
  saffron:   '#E3B505',
  dark:      '#3A3A3C',
};

const LANG = {
  en: {
    appName: '❤️U Festival',
    appDates: '15–16 August 2026 · Utrecht',
    location: 'Grasweide Strijkviertel, Utrecht',
    home: 'Home', info: 'Info', schedule: 'Schedule', map: 'Map',
    // Home
    liveUpdates: 'Live Updates',
    urgent: 'URGENT',
    pullToRefresh: 'Pull to refresh',
    releaseToRefresh: 'Release to refresh',
    refreshing: 'Refreshing…',
    noNewsTitle: 'No news at this moment',
    noNewsDesc: 'Live announcements, weather alerts and stage updates will appear here during the festival.',
    festivalStarts: 'Festival starts in',
    days: 'Days', hours: 'Hours', minutes: 'Mins', seconds: 'Secs',
    newsTitle1: 'Weather update', newsBody1: 'Sunny all weekend — 24°C. Don\'t forget sunscreen and water!', newsTime1: '2h ago',
    newsTitle2: 'Stage change: Dotan', newsBody2: 'Dotan\'s set moves 15 min later. New time: 19:15 at Ponton.', newsTime2: '15 min ago', urgentNews: 'URGENT',
    newsTitle3: 'Welcome to ❤️U 2026!', newsBody3: 'Gates open at 10:00 both days. Have an unforgettable weekend.', newsTime3: '1d ago',
    // Info
    infoTitle: 'Festival Info',
    infoVipTag: 'VIP perks',
    infoFacts: [
      { icon: 'event',    label: 'Dates',      value: '15–16 August 2026' },
      { icon: 'schedule', label: 'Open daily', value: '12:00 – 23:00' },
      { icon: 'place',    label: 'Location',   value: 'Strijkviertel, Utrecht' },
    ],
    sec1Title: 'General & Contact',
    sec1Body: '❤️U Festival is for new students in the Utrecht region and is a complement to UIT.\n\nLocation: Strijkviertel, Utrecht\nNavigation: Strijkviertelweg, Utrecht\nDate: Saturday 15 & Sunday 16 August 2026\nHours: 12:00 – 23:00',
    sec2Title: 'Getting There',
    sec2Items: [
      {t:'Bicycle', b:'Plenty of free bike parking at the venue entrance.'},
      {t:'Car (P+R)', b:'Use P+R Papendorp. 10-min walk to the festival grounds.'},
      {t:'Public transport', b:'Plan your route via 9292.nl. Closest stop: Strijkviertel.'},
      {t:'Shuttle bus', b:'Utrecht Centraal → Mineurslaan. Runs 12:00–19:00 (out) and until 21:00 (back). Free with wristband.'},
      {t:'Taxi & Kiss & Ride', b:'Drop-off zone at Mineurslaan entrance.'},
    ],
    sec3Title: 'Lockers',
    sec3Body: 'Medium and large lockers available on the festival grounds. No online reservation required — first come, first served. Fits 3–4 jackets comfortably.',
    sec4Title: 'FAQ',
    sec4Items: [
      {t:'Can I bring medication?', b:'Yes, with a doctor\'s note at the entrance check.'},
      {t:'Can I leave and come back?', b:'No — the site is single-entry. Plan ahead!'},
      {t:'Are there lockers available?', b:'Yes — see the Lockers section above.'},
    ],
    sec5Title: 'Golden-GLU',
    sec5Body: 'GLU students receive a golden wristband — your key to the golden toilets and VIP order points without queues. Show your GLU card at the Info Tent to collect yours.',
    // Schedule
    scheduleTitle: 'Schedule',
    scheduleOffline: 'Offline — showing saved schedule',
    close: 'Close',
    day1: 'Sat 15 Aug', day2: 'Sun 16 Aug',
    nowPlaying: 'NOW PLAYING',
    favorited: 'Favorited',
    favorite: 'Favorite',
    watchVideo: 'Watch on YouTube',
    setReminder: 'Set reminder',
    reminderSet: 'Reminder set ✓',
    min15: '15 min', min10: '10 min', min5: '5 min',
    before: 'before',
    toastMsg: 'begins in 15 minutes at Ponton',
    // Map
    mapTitle: 'Map',
    yourLocation: 'Your location',
    enableGPS: 'Enable location to see yourself on the map',
    gpsDenied: 'Location access denied. Enable it in your browser settings.',
    gpsUnsupported: 'Location is not supported on this device.',
    gpsOutside: 'You appear to be outside the festival grounds.',
    liveBadge: 'LIVE',
    showLegend: 'Legend',
    legend: 'Legend',
    tapForDetails: 'Tap a marker for details',
    // Markers
    markerPonton: 'Ponton · Main Stage',
    markerLake: 'The Lake · Talent stage',
    markerClub: 'The Club · Theater & Comedy',
    markerHangaar: 'Hangaar · DJ & Dance',
    markerToilet: 'Toilets',
    markerIce: 'Ice Cream',
    markerBar: 'Bar',
    markerFood: 'Food',
    markerMerch: 'Merchandise',
    markerLocker: 'Lockers',
    markerAid: 'First Aid (EHBO)',
    markerEntry: 'Entrance / Exit',
    mPontonD: 'Main festival stage. Capacity 5,000.',
    mLakeD: 'Talent stage by the waterfront.',
    mClubD: 'Comedy, lectures, theater and movies.',
    mHangaarD: 'DJ sets and dance floor. Open until 23:45.',
    mToiletD: 'Toilets and gender-neutral facilities.',
    mIceD: 'Ice cream stands. Open 12:00–22:00.',
    mBarD: 'Draft beer, wine, soda and non-alcoholic options.',
    mFoodD: 'Food trucks with veggie, vegan and gluten-free options.',
    mMerchD: 'Festival merch: shirts, caps, totes and more.',
    mLockerD: 'Medium & large lockers. Fits 3–4 jackets.',
    mAidD: 'Medical assistance, 24/7 during festival hours.',
    mEntryD: 'Main entrance & exit. Ticket check here.',
  },
  nl: {
    appName: '❤️U Festival',
    appDates: '15–16 augustus 2026 · Utrecht',
    location: 'Grasweide Strijkviertel, Utrecht',
    home: 'Home', info: 'Info', schedule: 'Schema', map: 'Kaart',
    liveUpdates: 'Live Updates',
    urgent: 'URGENT',
    pullToRefresh: 'Trek omlaag om te vernieuwen',
    releaseToRefresh: 'Laat los om te vernieuwen',
    refreshing: 'Vernieuwen…',
    noNewsTitle: 'Geen nieuws op dit moment',
    noNewsDesc: 'Live aankondigingen, weerwaarschuwingen en podiumwijzigingen verschijnen hier tijdens het festival.',
    festivalStarts: 'Festival begint over',
    days: 'Dagen', hours: 'Uren', minutes: 'Min', seconds: 'Sec',
    newsTitle1: 'Weer update', newsBody1: 'Zonnig het hele weekend — 24°C. Vergeet je zonnebrand en water niet!', newsTime1: '2u geleden',
    newsTitle2: 'Podiumwijziging: Dotan', newsBody2: 'Dotan\'s set verplaatst 15 min later. Nieuwe tijd: 19:15 op Ponton.', newsTime2: '15 min geleden', urgentNews: 'URGENT',
    newsTitle3: 'Welkom bij ❤️U 2026!', newsBody3: 'Poorten open om 10:00 beide dagen. Geniet van een onvergetelijk weekend.', newsTime3: '1d geleden',
    infoTitle: 'Festival Info',
    infoVipTag: 'VIP-voordelen',
    infoFacts: [
      { icon: 'event',    label: 'Datum',          value: '15–16 augustus 2026' },
      { icon: 'schedule', label: 'Dagelijks open', value: '12:00 – 23:00' },
      { icon: 'place',    label: 'Locatie',        value: 'Strijkviertel, Utrecht' },
    ],
    sec1Title: 'Algemeen & Contact',
    sec1Body: '❤️U Festival is voor nieuwe studenten in de regio Utrecht en is een aanvulling op UIT.\n\nLocatie: Strijkviertel, Utrecht\nNavigatie: Strijkviertelweg, Utrecht\nDatum: Zaterdag 15 & Zondag 16 augustus 2026\nTijden: 12:00 – 23:00',
    sec2Title: 'Bereikbaarheid',
    sec2Items: [
      {t:'Fiets', b:'Volop gratis fietsparkeerplekken bij de ingang.'},
      {t:'Auto (P+R)', b:'Gebruik P+R Papendorp. 10 min lopen naar het festivalterrein.'},
      {t:'Openbaar vervoer', b:'Plan je route via 9292.nl. Dichtstbijzijnde halte: Strijkviertel.'},
      {t:'Shuttlebus', b:'Utrecht Centraal → Mineurslaan. Rijdt 12:00–19:00 (heen) en tot 21:00 (terug). Gratis met polsband.'},
      {t:'Taxi & Kiss & Ride', b:'Afzetzone bij ingang Mineurslaan.'},
    ],
    sec3Title: 'Lockers',
    sec3Body: 'Medium en grote lockers beschikbaar op het festivalterrein. Geen online reservering nodig — wie het eerst komt, wie het eerst maalt. Passen 3–4 jassen makkelijk.',
    sec4Title: 'FAQ',
    sec4Items: [
      {t:'Mag ik medicatie meenemen?', b:'Ja, met een doktersverklaring bij de ingangscontrole.'},
      {t:'Mag ik tussendoor weggaan?', b:'Nee — het terrein is single-entry. Plan vooruit!'},
      {t:'Zijn er lockers beschikbaar?', b:'Ja — zie de Lockers sectie hierboven.'},
    ],
    sec5Title: 'Golden-GLU',
    sec5Body: 'GLU-studenten ontvangen een gouden armbandje — jouw toegang tot de gouden toiletten en VIP-bestelpunten zonder rij. Laat je GLU-pas zien bij de Info Tent om het op te halen.',
    scheduleTitle: 'Schema',
    scheduleOffline: 'Offline — opgeslagen schema',
    close: 'Sluiten',
    day1: 'Za 15 aug', day2: 'Zo 16 aug',
    nowPlaying: 'NU LIVE',
    favorited: 'Favoriet',
    favorite: 'Favoriet',
    watchVideo: 'Bekijk op YouTube',
    setReminder: 'Herinnering instellen',
    reminderSet: 'Herinnering ingesteld ✓',
    min15: '15 min', min10: '10 min', min5: '5 min',
    before: 'vooraf',
    toastMsg: 'begint over 15 minuten op Ponton',
    mapTitle: 'Kaart',
    yourLocation: 'Jouw locatie',
    enableGPS: 'Zet locatietoegang aan om jezelf te zien',
    gpsDenied: 'Locatietoegang geweigerd. Zet het aan in je browserinstellingen.',
    gpsUnsupported: 'Locatie wordt niet ondersteund op dit apparaat.',
    gpsOutside: 'Je lijkt buiten het festivalterrein te zijn.',
    liveBadge: 'LIVE',
    showLegend: 'Legenda',
    legend: 'Legenda',
    tapForDetails: 'Tik op een marker voor details',
    markerPonton: 'Ponton · Hoofdpodium',
    markerLake: 'The Lake · Talentpodium',
    markerClub: 'The Club · Theater & Comedy',
    markerHangaar: 'Hangaar · DJ & Dance',
    markerToilet: 'Toiletten',
    markerIce: 'IJs',
    markerBar: 'Bar',
    markerFood: 'Eten',
    markerMerch: 'Merchandise',
    markerLocker: 'Lockers',
    markerAid: 'EHBO',
    markerEntry: 'In-/Uitgang',
    mPontonD: 'Het hoofdpodium. Capaciteit 5.000.',
    mLakeD: 'Talentpodium aan het water.',
    mClubD: 'Comedy, lezingen, theater en films.',
    mHangaarD: 'DJ sets en dansvloer. Open tot 23:45.',
    mToiletD: 'Toiletten en genderneutrale voorzieningen.',
    mIceD: 'IJskramen. Open 12:00–22:00.',
    mBarD: 'Biertap, wijn, frisdrank en non-alcoholisch.',
    mFoodD: 'Foodtrucks met vega, vegan en glutenvrije opties.',
    mMerchD: 'Festival merch: shirts, petten, totes en meer.',
    mLockerD: 'Medium en grote lockers. Past 3–4 jassen.',
    mAidD: 'Medische hulp, 24/7 tijdens festivaltijden.',
    mEntryD: 'Hoofdingang & uitgang. Ticketcontrole hier.',
  }
};

// Artist bios (shared across langs — placeholder en)
const ARTISTS = {
  'Armin van Buuren':   { genre:'Trance',            bio:"Five-time World's No. 1 DJ, euphoric festival sets." },
  'Kensington':         { genre:'Indie Rock',        bio:'Rotterdam quintet. Soaring choruses, arena-ready hooks.' },
  'De Staat':           { genre:'Experimental Rock', bio:'Nijmegen. Funky grooves, theatrical stagecraft.' },
  'Navarone':           { genre:'Rock',              bio:"Utrecht's own. Raw intensity, riff-driven anthems." },
  'Dotan':              { genre:'Folk-Pop',          bio:'Intimate voice, heartfelt storytelling, platinum sales.' },
  'Froukje':            { genre:'Pop',               bio:'Candid lyrics, synth hooks, voice of her generation.' },
  'Martin Garrix':      { genre:'EDM',               bio:'Broke through as teen with "Animals," stadium-sized drops.' },
  'Within Temptation':  { genre:'Symphonic Metal',   bio:'Sharon den Adel. Cinematic soundscapes, operatic vocals.' },
  "Chef'Special":       { genre:'Funk-Pop',          bio:'Haarlem four-piece. Genre-fluid, joyous live shows.' },
  'Eefje de Visser':    { genre:'Indie-Pop',         bio:'Hypnotic vocals, dreamlike twilight-festival vibe.' },
  'Spinvis':            { genre:'Lo-fi Indie',       bio:'Poetic collage-songs, surreal live experiences.' },
};

// Schedule — day 1 = Sat, day 2 = Sun. Stage index: 0=Ponton 1=Lake 2=Club 3=Hangaar
const STAGES = ['Ponton', 'The Lake', 'The Club', 'Hangaar'];
// kind: 'main' vermilion, 'talent' cerulean, 'club' saffron, 'dj' dark
// Schedule rebuilt from blokkenschema.pdf (Voorlopig blokkenschema LoveU Festival 2026)
const SCHEDULE = {
  1: [
    // Ponton (main)
    {id:'s1a1', s:0, k:'main',   name:'Armin van Buuren', start:'10:30', end:'12:00'},
    {id:'s1a2', s:0, k:'main',   name:'Kensington',       start:'12:30', end:'14:00'},
    {id:'s1a3', s:0, k:'main',   name:'De Staat',         start:'14:30', end:'16:30'},
    {id:'s1a4', s:0, k:'main',   name:'Navarone',         start:'17:00', end:'18:30'},
    {id:'s1a5', s:0, k:'main',   name:'Dotan',            start:'19:15', end:'21:15'},
    {id:'s1a6', s:0, k:'main',   name:'Froukje',          start:'22:00', end:'24:00'},
    // The Lake (talent)
    {id:'s1b1', s:1, k:'talent', name:'Talent set 1', start:'10:00', end:'11:00'},
    {id:'s1b2', s:1, k:'talent', name:'Talent set 2', start:'11:30', end:'13:00'},
    {id:'s1b3', s:1, k:'talent', name:'Talent set 3', start:'13:30', end:'15:00'},
    {id:'s1b4', s:1, k:'talent', name:'Talent set 4', start:'15:30', end:'17:00'},
    {id:'s1b5', s:1, k:'talent', name:'Talent set 5', start:'17:30', end:'18:30'},
    {id:'s1b6', s:1, k:'talent', name:'Talent set 6', start:'19:15', end:'20:45'},
    {id:'s1b7', s:1, k:'talent', name:'Talent set 7', start:'21:30', end:'23:00'},
    // The Club (theater/comedy)
    {id:'s1c1', s:2, k:'club', name:'Comedy',      start:'12:15', end:'13:00'},
    {id:'s1c2', s:2, k:'club', name:'Lecture',     start:'13:45', end:'14:30'},
    {id:'s1c3', s:2, k:'club', name:'Theater',     start:'15:15', end:'16:45'},
    {id:'s1c4', s:2, k:'club', name:'Movie',       start:'17:30', end:'19:30'},
    {id:'s1c5', s:2, k:'club', name:'Performance', start:'20:15', end:'21:15'},
    {id:'s1c6', s:2, k:'club', name:'Illusionist', start:'22:00', end:'23:00'},
    // Hangaar (DJ)
    {id:'s1d1', s:3, k:'dj',   name:'DJ set 1', start:'10:00', end:'11:00'},
    {id:'s1d2', s:3, k:'dj',   name:'DJ set 2', start:'11:00', end:'12:30'},
    {id:'s1d3', s:3, k:'dj',   name:'DJ set 3', start:'12:30', end:'14:00'},
    {id:'s1d4', s:3, k:'dj',   name:'DJ set 4', start:'14:00', end:'15:30'},
    {id:'s1d5', s:3, k:'dj',   name:'DJ set 5', start:'15:30', end:'17:30'},
    {id:'s1d6', s:3, k:'dj',   name:'DJ set 6', start:'17:30', end:'19:30'},
    {id:'s1d7', s:3, k:'dj',   name:'DJ set 7', start:'19:30', end:'21:30'},
    {id:'s1d8', s:3, k:'dj',   name:'DJ set 8', start:'21:30', end:'24:00'},
  ],
  2: [
    // Ponton (main)
    {id:'s2a1', s:0, k:'main',   name:'Martin Garrix',     start:'11:00', end:'13:00'},
    {id:'s2a2', s:0, k:'main',   name:'Within Temptation', start:'13:45', end:'15:45'},
    {id:'s2a3', s:0, k:'main',   name:"Chef'Special",      start:'16:30', end:'18:30'},
    {id:'s2a4', s:0, k:'main',   name:'Eefje de Visser',   start:'19:15', end:'21:15'},
    {id:'s2a5', s:0, k:'main',   name:'Spinvis',           start:'22:00', end:'24:00'},
    // The Lake (talent)
    {id:'s2b1', s:1, k:'talent', name:'Talent set 1', start:'10:00', end:'11:00'},
    {id:'s2b2', s:1, k:'talent', name:'Talent set 2', start:'11:30', end:'13:00'},
    {id:'s2b3', s:1, k:'talent', name:'Talent set 3', start:'13:30', end:'15:00'},
    {id:'s2b4', s:1, k:'talent', name:'Talent set 4', start:'15:30', end:'17:30'},
    {id:'s2b5', s:1, k:'talent', name:'Talent set 5', start:'18:15', end:'19:45'},
    {id:'s2b6', s:1, k:'talent', name:'Talent set 6', start:'20:30', end:'22:30'},
    // The Club (theater/comedy)
    {id:'s2c1', s:2, k:'club', name:'Comedy',     start:'12:00', end:'12:45'},
    {id:'s2c2', s:2, k:'club', name:'Lecture',    start:'13:30', end:'14:30'},
    {id:'s2c3', s:2, k:'club', name:'Theater',    start:'15:30', end:'16:30'},
    {id:'s2c4', s:2, k:'club', name:'Movie',      start:'17:30', end:'19:30'},
    {id:'s2c5', s:2, k:'club', name:'Magic Show', start:'20:15', end:'21:45'},
    // Hangaar (DJ)
    {id:'s2d1', s:3, k:'dj',   name:'DJ set 1', start:'10:00', end:'10:30'},
    {id:'s2d2', s:3, k:'dj',   name:'DJ set 2', start:'10:30', end:'12:30'},
    {id:'s2d3', s:3, k:'dj',   name:'DJ set 3', start:'12:30', end:'13:30'},
    {id:'s2d4', s:3, k:'dj',   name:'DJ set 4', start:'13:30', end:'15:30'},
    {id:'s2d5', s:3, k:'dj',   name:'DJ set 5', start:'15:30', end:'17:00'},
    {id:'s2d6', s:3, k:'dj',   name:'DJ set 6', start:'17:00', end:'18:30'},
    {id:'s2d7', s:3, k:'dj',   name:'DJ set 7', start:'18:30', end:'21:00'},
    {id:'s2d8', s:3, k:'dj',   name:'DJ set 8', start:'21:00', end:'24:00'},
  ]
};

const KIND_COLOR = (k) => k === 'main' ? BRAND.vermilion : k === 'talent' ? BRAND.cerulean : k === 'club' ? BRAND.saffron : BRAND.dark;

function timeToY(t) {
  const [h, m] = t.split(':').map(Number);
  return (h - 10 + m / 60) * 80; // PX_PER_HOUR 80, start 10:00
}
function dur(s, e) {
  const [sh, sm] = s.split(':').map(Number);
  const [eh, em] = e.split(':').map(Number);
  return (eh + em/60) - (sh + sm/60);
}

export { BRAND, LANG, ARTISTS, SCHEDULE, STAGES, KIND_COLOR, timeToY, dur };
